-- AlterTable: Add regulator verification kill-switch flags to SystemSettings
ALTER TABLE "SystemSettings" ADD COLUMN IF NOT EXISTS "enableAutoVerifyNCA" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "enableAutoVerifyEPRA" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "enableAutoVerifyBORAQS" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "enableAutoVerifyEBK" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "enableAutoVerifyEARB" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "enableAutoVerifyVRB" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "enableAutoVerifyISK" BOOLEAN NOT NULL DEFAULT false;
