# Standard client TCP port
port: 4222

# WebSocket listener for Render HTTP/HTTPS reverse proxy
websocket {
  port: 10000
  no_tls: true
}

# HTTP Monitoring & Health Check
http_port: 8222

# JetStream enabled
jetstream {
  store_dir: "/data/jetstream"
}

# Token Authentication
authorization {
  token: "SUAJ2SX4XF2GRT7XTY7R46T5A7Y4YX7E2QRRY63K42DOB5R4K43RSY23IQ"
}
