name = "build-market-client"
main = "apps/client/.open-next/worker.js"
compatibility_date = "2026-04-18"
compatibility_flags = ["nodejs_compat"]

[build]
command = "pnpm run client:build:cloudflare-worker"

[assets]
directory = "apps/client/.open-next/assets"
binding = "ASSETS"

[observability]
enabled = true
